// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwoq4iWfS6QOapo37mdWcpNgtwwig10fo',
    appId: '1:283535250986:web:b17f55998691e34d2c9553',
    messagingSenderId: '283535250986',
    projectId: 'e-cart-39857',
    authDomain: 'e-cart-39857.firebaseapp.com',
    storageBucket: 'e-cart-39857.firebasestorage.app',
    measurementId: 'G-K09RZ0YFP1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu52e8SwNq-XbzCFCHysA-lQvMvyLYASQ',
    appId: '1:283535250986:android:be1848dd6d1c20cd2c9553',
    messagingSenderId: '283535250986',
    projectId: 'e-cart-39857',
    storageBucket: 'e-cart-39857.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuQ0H_gzLqZIAhfsURTVwlyr3CqkT6MZ8',
    appId: '1:283535250986:ios:fb5b91fffc7d17752c9553',
    messagingSenderId: '283535250986',
    projectId: 'e-cart-39857',
    storageBucket: 'e-cart-39857.firebasestorage.app',
    iosBundleId: 'com.example.ecart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuQ0H_gzLqZIAhfsURTVwlyr3CqkT6MZ8',
    appId: '1:283535250986:ios:fb5b91fffc7d17752c9553',
    messagingSenderId: '283535250986',
    projectId: 'e-cart-39857',
    storageBucket: 'e-cart-39857.firebasestorage.app',
    iosBundleId: 'com.example.ecart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwoq4iWfS6QOapo37mdWcpNgtwwig10fo',
    appId: '1:283535250986:web:005941e9ac824d532c9553',
    messagingSenderId: '283535250986',
    projectId: 'e-cart-39857',
    authDomain: 'e-cart-39857.firebaseapp.com',
    storageBucket: 'e-cart-39857.firebasestorage.app',
    measurementId: 'G-5XCWTDPG9R',
  );
}
